/* ---------------- 探究学習アンケート分析モジュール ----------------
 * 依存: script.js が定義する COLOR / el() / darkTooltip() / Chart(グローバル)
 * データソース: output/kokorozashi_survey_2026_tagged.js が定義する
 *              window.KOKOROZASHI_DATA（generated by scripts/aggregate_kokorozashi_survey.py）
 */

// data.policy_labels（大綱の政策1〜政策15、aggregate_kokorozashi_survey.pyが出力）を
// 唯一の正として参照する。ラベルのハードコード重複を避けるため、値は
// mainKokorozashi() 実行時にセットする。
let POLICY_TAG_LABELS = {};

// 「大綱の政策で絞り込み」フィルタの現在値（policyN、未選択時はnull）。
// ヒートマップ・要強化項目・アントレプレナーシップ指標の3セクションに横断的に効く。
let kokorozashiData = null;
let activePolicyFilter = null;

function matchesPolicyFilter(tags) {
  return !activePolicyFilter || (tags || []).includes(activePolicyFilter);
}

// 表示用に政策タグを番号の若い順（政策1→政策15）に並べ替える。
function sortedPolicyTags(tags) {
  return [...(tags || [])].sort((a, b) => parseInt(a.replace("policy", ""), 10) - parseInt(b.replace("policy", ""), 10));
}

/* pt(ポイント差)を符号付きバーで表示する共通コンポーネント（伸びている項目用）。
   funnel-list のCSSクラスを流用しつつ、正負で色を出し分ける。 */
function renderPtBarList(containerId, items) {
  const container = document.getElementById(containerId);
  if (!container) return;
  container.innerHTML = "";
  if (!items.length) return;
  const maxAbs = Math.max(...items.map((i) => Math.abs(i.pt))) || 1;
  items.forEach((item) => {
    const row = el("div", "funnel-row");
    row.appendChild(el("div", "funnel-label", item.label));
    const barRow = el("div", "funnel-bar-row");
    const track = el("div", "funnel-track");
    const fill = el("div", "funnel-fill");
    const positive = item.pt >= 0;
    fill.style.setProperty("--bar-color", positive ? COLOR.good : COLOR.warn);
    fill.style.width = `${Math.max((Math.abs(item.pt) / maxAbs) * 100, 6)}%`;
    track.appendChild(fill);
    barRow.appendChild(track);
    barRow.appendChild(el("div", "funnel-value", `${positive ? "+" : ""}${item.pt}pt`));
    row.appendChild(barRow);
    container.appendChild(row);
  });
}

/* 現在値(2026年度%)を100点満点のバーで表示する共通コンポーネント（課題の項目用）。
   全国トレンド比の符号にかかわらず「絶対値が低い」ことを一貫して警告色で示す。
   （例: No.41は伸び幅は大きい(+5.3pt)が絶対値55.6%はなお低い、というケースを
   　　　トレンド値でバー表示すると好転しているように誤読されるため）
   全国トレンド比は設問文の折り返しラベルに埋め込まず、右側の数値欄に
   小さな2行目として添える（ラベルの折り返し行数が項目ごとにばらつくと
   バーの位置が左右の項目間で揃わなくなるため）。 */
function renderLevelBarList(containerId, items) {
  const container = document.getElementById(containerId);
  if (!container) return;
  container.innerHTML = "";
  if (!items.length) return;
  items.forEach((item) => {
    const row = el("div", "funnel-row");
    row.appendChild(el("div", "funnel-label", item.label));
    const barRow = el("div", "funnel-bar-row");
    const track = el("div", "funnel-track");
    const fill = el("div", "funnel-fill");
    fill.style.setProperty("--bar-color", COLOR.warn);
    fill.style.width = `${Math.max(item.value, 6)}%`;
    track.appendChild(fill);
    barRow.appendChild(track);
    const valueBox = el("div", "funnel-value");
    valueBox.appendChild(el("span", null, `${item.value}%`));
    if (item.trend !== undefined && item.trend !== null) {
      valueBox.appendChild(el("span", "funnel-value-sub", `全国トレンド比 ${item.trend >= 0 ? "+" : ""}${item.trend}pt`));
    }
    barRow.appendChild(valueBox);
    row.appendChild(barRow);
    container.appendChild(row);
  });
}

function renderKokorozashiGrowth(data) {
  const growth = data.trait_layer_growth || [];
  if (!growth.length) return;

  new Chart(document.getElementById("chart-kokorozashi-growth"), {
    type: "bar",
    data: {
      labels: growth.map((g) => g.trait),
      datasets: [{
        label: "2024→2026年度 伸び(pt)",
        data: growth.map((g) => g.avg_growth_2024_2026),
        backgroundColor: "#9163b6",
        borderRadius: 4,
      }],
    },
    options: {
      responsive: true, maintainAspectRatio: false,
      plugins: { legend: { display: false }, tooltip: darkTooltip({ callbacks: { label: (ctx) => `+${ctx.raw}pt` } }) },
      scales: {
        x: { grid: { display: false }, ticks: { color: COLOR.textSub } },
        y: { beginAtZero: true, grid: { color: COLOR.gridLine }, ticks: { color: COLOR.textSub, callback: (v) => `+${v}` } },
      },
    },
  });

  const top = [...growth].sort((a, b) => b.avg_growth_2024_2026 - a.avg_growth_2024_2026)[0];
  const noteEl = document.getElementById("kokorozashi-growth-note");
  if (noteEl && top) {
    const tie = top.trait === "社会性"
      ? "大綱の「地域や家庭で共に学び支え合う社会の実現」の取組と重なる伸びである。"
      : `大綱の政策との対応関係は下記の要強化項目カードを参照。`;
    noteEl.textContent = `最も伸びているのは${top.trait}（+${top.avg_growth_2024_2026}pt）。${tie}`;
  }
}

function renderEntrepreneurship(data) {
  const d = data.entrepreneurship;
  if (!d) return;
  document.getElementById("kokorozashi-entre-summary").textContent = d.summary;

  const strengths = d.strengths.filter((s) => matchesPolicyFilter(s.policy_tags));
  const weaknesses = d.weaknesses.filter((w) => matchesPolicyFilter(w.policy_tags));

  renderPtBarList(
    "list-entre-strength",
    strengths.map((s) => ({ label: `No.${s.no} ${s.text}`, pt: s.yoy_diff })),
  );
  renderLevelBarList(
    "list-entre-weakness",
    weaknesses.map((w) => ({
      label: `No.${w.no} ${w.text}`,
      value: w.v2026,
      trend: w.national_trend_diff,
    })),
  );
}

/* ---------------- 多様性・地域みらい留学の影響 ----------------
   「違いを認め合う文化」（No.22/23）と「地域とのつながり」（No.69/70）の
   2024→2026年度推移を折れ線グラフ＋独自凡例で表示する。折れ線グラフ本体は
   1回だけ描画し（データは年度更新まで変わらないため）、政策フィルタの
   切り替えではカード全体の明暗（policy-scope-dimmed）のみ更新する。 */
const DIVERSITY_LINE_COLORS = {
  culture: [COLOR.overview, COLOR.career],
  community: [COLOR.good, "#3d7a42"],
};

function renderDiversityLegend(containerId, questions, colors, { strength = false } = {}) {
  const container = document.getElementById(containerId);
  if (!container || container.dataset.rendered) return;
  questions.forEach((q, i) => {
    const row = el("div", `diversity-legend-row${strength ? " strength" : ""}`);
    const dot = el("span", "diversity-legend-dot");
    dot.style.background = colors[i % colors.length];
    row.appendChild(dot);
    row.appendChild(el("span", "diversity-legend-text", `No.${q.no} ${q.text}`));
    const selfDiff = Math.round((q.school["2026"] - q.school["2024"]) * 10) / 10;
    const diffText = strength
      ? `自校${selfDiff >= 0 ? "+" : ""}${selfDiff}pt（全国トレンド比${q.national_trend_diff >= 0 ? "+" : ""}${q.national_trend_diff}pt）`
      : `自校${selfDiff >= 0 ? "+" : ""}${selfDiff}pt`;
    row.appendChild(el("span", "diversity-legend-diff", diffText));
    container.appendChild(row);
  });
  container.dataset.rendered = "1";
}

function renderDiversityLineChart(canvasId, questions, colors, fill) {
  const canvas = document.getElementById(canvasId);
  if (!canvas || !questions.length || Chart.getChart(canvas)) return;
  new Chart(canvas, {
    type: "line",
    data: {
      labels: ["2024", "2025", "2026"],
      datasets: questions.map((q, i) => ({
        label: `No.${q.no}`,
        data: ["2024", "2025", "2026"].map((y) => q.school[y]),
        borderColor: colors[i % colors.length],
        backgroundColor: fill ? `${colors[i % colors.length]}26` : colors[i % colors.length],
        borderWidth: 2,
        tension: 0.3,
        pointRadius: 3,
        pointHoverRadius: 5,
        fill: fill ? (i === 0 ? "origin" : false) : false,
      })),
    },
    options: {
      responsive: true, maintainAspectRatio: false,
      scales: {
        x: { grid: { display: false }, ticks: { color: COLOR.textSub } },
        y: { beginAtZero: true, max: 100, grid: { color: COLOR.gridLine }, ticks: { color: COLOR.textSub, callback: (v) => `${v}%` } },
      },
      plugins: {
        legend: { display: false },
        tooltip: darkTooltip({ callbacks: { label: (ctx) => `${ctx.dataset.label}: ${ctx.raw}%` } }),
      },
    },
  });
}

function renderDiversityImpact(data) {
  const d = data.diversity_impact;
  if (!d) return;

  const card = document.getElementById("card-diversity-impact");
  if (card) card.classList.toggle("policy-scope-dimmed", !matchesPolicyFilter(d.policy_tags));

  const tagsEl = document.getElementById("diversity-tags");
  if (tagsEl && !tagsEl.dataset.rendered) {
    sortedPolicyTags(d.policy_tags).forEach((t) => {
      tagsEl.appendChild(el("span", "policy-tag", POLICY_TAG_LABELS[t] || t));
    });
    tagsEl.dataset.rendered = "1";
  }

  renderDiversityLegend("diversity-culture-legend", d.culture.questions, DIVERSITY_LINE_COLORS.culture);
  renderDiversityLineChart("chart-diversity-culture", d.culture.questions, DIVERSITY_LINE_COLORS.culture, false);
  document.getElementById("diversity-culture-note").textContent = d.culture.note;

  renderDiversityLegend("diversity-community-legend", d.community.questions, DIVERSITY_LINE_COLORS.community, { strength: true });
  renderDiversityLineChart("chart-diversity-community", d.community.questions, DIVERSITY_LINE_COLORS.community, true);
  document.getElementById("diversity-community-note").textContent = d.community.note;

  const ref = document.getElementById("diversity-ref");
  if (ref && d.collaboration_ref && !ref.dataset.rendered) {
    const g = d.collaboration_ref;
    ref.appendChild(document.createTextNode(
      `参考指標: ${g.trait}の5層平均は2024→2026年度で${g.avg_growth_2024_2026 >= 0 ? "+" : ""}${g.avg_growth_2024_2026}pt伸びており（`
    ));
    const link = el("a", null, "4資質の伸びを見る");
    link.href = "#card-kokorozashi-growth";
    ref.appendChild(link);
    ref.appendChild(document.createTextNode("）、多様な背景の生徒同士の関わり合いの増加と整合的である。"));
    ref.dataset.rendered = "1";
  }
}

function renderWeakPoints(data) {
  const points = data.weak_points.filter((w) => matchesPolicyFilter(w.policy_tags));
  document.getElementById("kokorozashi-weak-sub").textContent =
    `全国トレンド比 ${data.weak_threshold_pt}pt以下の設問（${points.length}件）｜ アンケート更新: ${data.source_updated}`;

  const list = document.getElementById("list-weak-points");
  list.innerHTML = "";
  points.forEach((w) => {
    const card = el("div", `weak-card${w.priority ? " priority" : ""}`);

    const head = el("div", "weak-card-head");
    head.appendChild(el("span", "weak-no", `No.${w.no}　${w.category_label}`));
    head.appendChild(el("span", "weak-trend", `${w.national_trend_diff}pt`));
    card.appendChild(head);

    card.appendChild(el("p", "weak-text", w.text));
    card.appendChild(el("div", "weak-value", `2026年度: ${w.v2026}%`));

    const tags = el("div", "policy-tags");
    sortedPolicyTags(w.policy_tags).forEach((t) => {
      tags.appendChild(el("span", "policy-tag", POLICY_TAG_LABELS[t] || t));
    });
    card.appendChild(tags);

    if (w.related_strengths.length) {
      const rel = w.related_strengths.map((r) => `${r.text}（+${r.national_trend_diff}pt）`).join("／");
      card.appendChild(el("p", "weak-related", `関連して伸びている項目: ${rel}`));
    }

    list.appendChild(card);
  });
}

/* ---------------- 層×資質マトリクス（ヒートマップ） ---------------- */
const HEATMAP_LAYERS = ["学習活動", "学習環境", "自己認識", "行動", "ウェルビーイング"];
const HEATMAP_TRAITS = ["主体性", "協働性", "探究性", "社会性"];
const HEATMAP_COLOR_STOPS = [
  [-1, [207, 81, 66]],   // --warn（下回る・強）
  [-0.5, [224, 168, 62]], // --c-finance（下回る・弱）
  [0, [64, 67, 74]],      // --track（同水準）
  [0.5, [62, 168, 168]],  // --c-career（上回る・弱）
  [1, [59, 130, 196]],    // --c-overview（上回る・強）
];
const HEATMAP_SATURATION_CAP = 20; // このptで色が最も濃くなる

function heatmapRgb(pt) {
  const t = Math.max(-1, Math.min(1, pt / HEATMAP_SATURATION_CAP));
  let lo = HEATMAP_COLOR_STOPS[0];
  let hi = HEATMAP_COLOR_STOPS[HEATMAP_COLOR_STOPS.length - 1];
  for (let i = 0; i < HEATMAP_COLOR_STOPS.length - 1; i++) {
    if (t >= HEATMAP_COLOR_STOPS[i][0] && t <= HEATMAP_COLOR_STOPS[i + 1][0]) {
      lo = HEATMAP_COLOR_STOPS[i];
      hi = HEATMAP_COLOR_STOPS[i + 1];
      break;
    }
  }
  const span = hi[0] - lo[0] || 1;
  const ratio = (t - lo[0]) / span;
  return lo[1].map((c, i) => Math.round(c + (hi[1][i] - c) * ratio));
}

// 背景色の相対輝度から読みやすい文字色（白/濃紺）を選ぶ（黄系セルでの視認性低下を防ぐ）
function readableTextColor(rgb) {
  const yiq = (rgb[0] * 299 + rgb[1] * 587 + rgb[2] * 114) / 1000;
  return yiq >= 150 ? "#14161a" : "#f5f6f7";
}

function renderHeatmapDetail(cat) {
  const detail = document.getElementById("kokorozashi-heatmap-detail");
  detail.innerHTML = "";
  detail.appendChild(el("h4", null, `${cat.label}（全国トレンド比 ${cat.national_trend_diff >= 0 ? "+" : ""}${cat.national_trend_diff}pt）`));
  if (cat.policy_tags.length) {
    const tags = el("div", "policy-tags");
    sortedPolicyTags(cat.policy_tags).forEach((t) => tags.appendChild(el("span", "policy-tag", POLICY_TAG_LABELS[t] || t)));
    detail.appendChild(tags);
  }
  const table = document.createElement("table");
  const thead = document.createElement("thead");
  thead.innerHTML = "<tr><th>設問</th><th>2026年度</th><th>全国トレンド比</th></tr>";
  table.appendChild(thead);
  const tbody = document.createElement("tbody");
  cat.questions.forEach((q) => {
    const tr = document.createElement("tr");
    const trend = q.national_trend_diff;
    const trendText = trend === null || trend === undefined ? "-" : `${trend >= 0 ? "+" : ""}${trend}pt`;
    tr.innerHTML = `<td>No.${q.no} ${q.text}</td><td>${q.school["2026"] ?? "-"}%</td><td>${trendText}</td>`;
    tbody.appendChild(tr);
  });
  table.appendChild(tbody);
  detail.appendChild(table);
}

function renderHeatmap(data) {
  const grid = document.getElementById("kokorozashi-heatmap");
  if (!grid) return;
  grid.innerHTML = "";

  const byKey = {};
  data.categories.forEach((c) => { if (c.trait) byKey[`${c.trait}_${c.layer}`] = c; });

  grid.appendChild(el("div", "heatmap-cell head"));
  HEATMAP_TRAITS.forEach((trait) => grid.appendChild(el("div", "heatmap-cell head", trait)));

  HEATMAP_LAYERS.forEach((layer) => {
    grid.appendChild(el("div", "heatmap-cell head row-head", layer));
    HEATMAP_TRAITS.forEach((trait) => {
      const cat = byKey[`${trait}_${layer}`];
      const cell = el("div", "heatmap-cell data");
      if (!cat) {
        cell.classList.add("empty");
        grid.appendChild(cell);
        return;
      }
      if (cat.national_trend_diff === null || cat.national_trend_diff === undefined) {
        cell.style.background = "rgba(255,255,255,0.06)";
      } else {
        const rgb = heatmapRgb(cat.national_trend_diff);
        cell.style.background = `rgb(${rgb.join(",")})`;
        cell.style.color = readableTextColor(rgb);
      }
      const orderedTags = sortedPolicyTags(cat.policy_tags);
      const policyNames = orderedTags.map((t) => POLICY_TAG_LABELS[t] || t).join(" ／ ");
      cell.title = `${cat.label}: 全国トレンド比 ${cat.national_trend_diff >= 0 ? "+" : ""}${cat.national_trend_diff}pt${policyNames ? ` ｜ ${policyNames}` : ""}（クリックで個別設問を表示）`;
      cell.tabIndex = 0;
      cell.setAttribute("role", "button");
      cell._policyTags = cat.policy_tags;
      if (!matchesPolicyFilter(cat.policy_tags)) cell.classList.add("dimmed");
      const value = el("div", "heatmap-value", `${cat.national_trend_diff >= 0 ? "+" : ""}${cat.national_trend_diff}pt`);
      cell.appendChild(value);
      if (orderedTags.length) {
        cell.appendChild(el("div", "heatmap-tags", orderedTags.map((t) => `政策${t.replace("policy", "")}`).join(" / ")));
      }
      const select = () => {
        grid.querySelectorAll(".heatmap-cell.selected").forEach((c) => c.classList.remove("selected"));
        cell.classList.add("selected");
        renderHeatmapDetail(cat);
      };
      cell.addEventListener("click", select);
      cell.addEventListener("keydown", (e) => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); select(); } });
      grid.appendChild(cell);
    });
  });
}

function applyHeatmapFilter() {
  const grid = document.getElementById("kokorozashi-heatmap");
  if (!grid) return;
  grid.querySelectorAll(".heatmap-cell.data").forEach((cell) => {
    if (cell.classList.contains("empty")) return;
    cell.classList.toggle("dimmed", !matchesPolicyFilter(cell._policyTags));
  });
}

/* ---------------- 大綱の政策で絞り込み ---------------- */
function updatePolicyFilterButtons() {
  const container = document.getElementById("kokorozashi-policy-filter");
  if (!container) return;
  container.querySelectorAll(".policy-filter-btn").forEach((btn) => {
    const isAllBtn = !btn.dataset.policy;
    btn.classList.toggle("active", isAllBtn ? activePolicyFilter === null : btn.dataset.policy === activePolicyFilter);
  });
}

function setPolicyFilter(key) {
  activePolicyFilter = key === null ? null : (activePolicyFilter === key ? null : key);
  updatePolicyFilterButtons();
  applyHeatmapFilter();
  renderWeakPoints(kokorozashiData);
  renderEntrepreneurship(kokorozashiData);
  renderDiversityImpact(kokorozashiData);
}

function renderPolicyFilter(data) {
  const container = document.getElementById("kokorozashi-policy-filter");
  if (!container) return;
  container.innerHTML = "";

  const used = new Set();
  data.categories.forEach((c) => (c.policy_tags || []).forEach((t) => used.add(t)));
  data.weak_points.forEach((w) => (w.policy_tags || []).forEach((t) => used.add(t)));
  if (data.entrepreneurship) {
    [...data.entrepreneurship.strengths, ...data.entrepreneurship.weaknesses].forEach((x) =>
      (x.policy_tags || []).forEach((t) => used.add(t))
    );
  }
  const ordered = Object.keys(POLICY_TAG_LABELS).filter((k) => used.has(k));

  const allBtn = el("button", "policy-filter-btn active", "すべて");
  allBtn.type = "button";
  allBtn.addEventListener("click", () => setPolicyFilter(null));
  container.appendChild(allBtn);

  ordered.forEach((key) => {
    const btn = el("button", "policy-filter-btn", `政策${key.replace("policy", "")}`);
    btn.type = "button";
    btn.dataset.policy = key;
    btn.title = POLICY_TAG_LABELS[key] || key;
    btn.addEventListener("click", () => setPolicyFilter(key));
    container.appendChild(btn);
  });
}

/* ---------------- 伸び幅ランキング ---------------- */
function renderGrowthRanking(data) {
  const r = data.growth_ranking;
  if (!r) return;

  const buildList = (containerId, items, isTop) => {
    const container = document.getElementById(containerId);
    container.innerHTML = "";
    items.forEach((item, i) => {
      const row = el("div", "rank-item");
      row.appendChild(el("div", "rank-order", `${i + 1}`));
      const body = el("div", "rank-body");
      body.appendChild(el("div", "rank-text", `No.${item.no} ${item.text}`));
      if (isTop && item.also_national_weak) {
        body.appendChild(el("div", "rank-note", "※全国トレンド比では要強化項目だが、自校では改善傾向"));
      } else if (!isTop && item.also_national_weak) {
        body.appendChild(el("div", "rank-note", "※要強化項目（全国トレンド比）にも該当"));
      }
      row.appendChild(body);
      const positive = item.yoy_diff >= 0;
      row.appendChild(el("div", `rank-value ${positive ? "positive" : "negative"}`, `${positive ? "+" : ""}${item.yoy_diff}pt`));
      container.appendChild(row);
    });
  };

  buildList("list-growth-top", r.top, true);
  buildList("list-growth-bottom", r.bottom, false);
}

/* ---------------- 県平均・全国平均との差分バブルチャート ---------------- */
let bubbleChartInstance = null;
let bubbleMode = "national";

function bubbleDatasetFor(data, mode) {
  const field = mode === "prefecture" ? "diff_prefecture_2026" : "diff_national_2026";
  const points = data.bubble_categories
    .filter((c) => c.v2026 !== null && c[field] !== null)
    .map((c) => ({ x: c.v2026, y: c[field], r: Math.max(6, Math.min(28, Math.abs(c[field]) * 1.3 + 6)), label: c.label, trait: c.trait }));
  const colors = { "主体性": COLOR.overview, "協働性": COLOR.activity, "探究性": COLOR.career, "社会性": COLOR.dorm };
  return points.map((p) => ({ ...p, color: colors[p.trait] || COLOR.neutral }));
}

function renderBubbleChart(data) {
  const canvas = document.getElementById("chart-kokorozashi-bubble");
  if (!canvas || !data.bubble_categories) return;

  const draw = (mode) => {
    const points = bubbleDatasetFor(data, mode);
    const label = mode === "prefecture" ? "県平均比" : "全国平均比";
    if (bubbleChartInstance) bubbleChartInstance.destroy();
    bubbleChartInstance = new Chart(canvas, {
      type: "bubble",
      data: {
        datasets: [{
          label,
          data: points.map((p) => ({ x: p.x, y: p.y, r: p.r })),
          backgroundColor: points.map((p) => `${p.color}99`),
          borderColor: points.map((p) => p.color),
          borderWidth: 1.5,
        }],
      },
      options: {
        responsive: true, maintainAspectRatio: false,
        plugins: {
          legend: { display: false },
          tooltip: darkTooltip({
            callbacks: {
              label: (ctx) => {
                const p = points[ctx.dataIndex];
                return `${p.label}：自校${p.x}% / ${label} ${p.y >= 0 ? "+" : ""}${p.y}pt`;
              },
            },
          }),
        },
        scales: {
          x: { title: { display: true, text: "2026年度 自校の値(%)", color: COLOR.textSub }, grid: { color: COLOR.gridLine }, ticks: { color: COLOR.textSub } },
          y: { title: { display: true, text: `${label}(pt)`, color: COLOR.textSub }, grid: { color: COLOR.gridLine }, ticks: { color: COLOR.textSub } },
        },
      },
    });
  };

  draw(bubbleMode);

  const toggle = document.getElementById("bubble-toggle");
  toggle.querySelectorAll(".bubble-toggle-btn").forEach((btn) => {
    btn.addEventListener("click", () => {
      toggle.querySelectorAll(".bubble-toggle-btn").forEach((b) => b.classList.remove("active"));
      btn.classList.add("active");
      bubbleMode = btn.dataset.mode;
      draw(bubbleMode);
    });
  });
}

/* ---------------- データの限界に関する注記 ---------------- */
function renderCaveat(data) {
  const el2 = document.getElementById("kokorozashi-caveat");
  if (!el2 || !data.data_limitations) return;
  el2.textContent = `※ ${data.data_limitations.join(" ")}`;
}

function mainKokorozashi() {
  const data = window.KOKOROZASHI_DATA;
  if (!data) return;
  kokorozashiData = data;
  POLICY_TAG_LABELS = data.policy_labels || {};

  document.getElementById("kokorozashi-growth-sub").textContent =
    `生徒アンケートの肯定的回答率・2年間の変化（回答者数 2026年度: ${data.respondents["2026"]}人）`;

  renderKokorozashiGrowth(data);
  renderPolicyFilter(data);
  renderHeatmap(data);
  renderGrowthRanking(data);
  renderBubbleChart(data);
  renderEntrepreneurship(data);
  renderDiversityImpact(data);
  renderWeakPoints(data);
  renderCaveat(data);
}

mainKokorozashi();
